model: resnet18
# dataset: imagenettewoof
# dataset: synthetic
dataset: imagenet
attribution_methods:
  - GradCAMPlusPlus
  - LayerCAM
  - ScoreCAM
metrics:
  - road_combined
  - deletioncurveauc
  - insertioncurveauc
  - infidelity
  - averagedrop
  - coherency
  - complexity
  # - roc_auc
  # - mass_iou
upscale_methods:
  - SimpleUpsampling
  # - ERFUpsamplingFast

# model_path: ./ResNet18_Syntetic.pth
output_path: ./results_resnet18_imagenet.csv
device: cuda:0
num_samples: 1000
